- id: '9422842052891'
  alias: Update Danfoss Ally TRV on change for trv.gf_kitchen
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_kitchen/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_kitchen/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_kitchen/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '8943084013873'
  alias: Update Danfoss Ally TRV on change for trv.uf_living-room_west
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_living-room_west/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_living-room_west/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_living-room_west/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '7389831631372'
  alias: Update Danfoss Ally TRV on change for trv.uf_living-room_north
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_living-room_north/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_living-room_north/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_living-room_north/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '2520211665129'
  alias: Update Danfoss Ally TRV on change for trv.gf_hw_west
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_hw_west/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_hw_west/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_hw_west/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '4445190419281'
  alias: Update Danfoss Ally TRV on change for trv.uf_office
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_office/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_office/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_office/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '8093688940434'
  alias: Update Danfoss Ally TRV on change for trv.gf_bath
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_bath/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_bath/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_bath/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '5086966581081'
  alias: Update Danfoss Ally TRV on change for trv.gf_hw_east
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_hw_east/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_hw_east/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_hw_east/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '2055359969470'
  alias: Update Danfoss Ally TRV on change for trv.gf_guest-room
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_guest-room/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_guest-room/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_guest-room/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '4774849798483'
  alias: Update Danfoss Ally TRV on change for trv.uf_bedroom
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_bedroom/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_bedroom/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_bedroom/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
- id: '1040536250765'
  alias: Update Danfoss Ally TRV on change for trv.gf_toilet
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_toilet/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '1'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_toilet/get
      payload: '{"occupied_heating_setpoint":""}'
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_toilet/get
      payload: '{"occupied_heating_setpoint":""}'
  mode: single
