- id: '8675595898642'
  alias: Update Danfoss Ally TRV on change for trv.gf_kitchen
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_kitchen/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_kitchen/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '7797130612005'
  alias: Update Danfoss Ally TRV on change for trv.uf_living-room_west
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_living-room_west/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_living-room_west/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '0160689663078'
  alias: Update Danfoss Ally TRV on change for trv.uf_living-room_north
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_living-room_north/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_living-room_north/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '7086098600118'
  alias: Update Danfoss Ally TRV on change for trv.gf_hw_west
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_hw_west/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_hw_west/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '2624334093968'
  alias: Update Danfoss Ally TRV on change for trv.uf_office
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_office/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_office/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '7718706237550'
  alias: Update Danfoss Ally TRV on change for trv.gf_bath
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_bath/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_bath/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '7995539510305'
  alias: Update Danfoss Ally TRV on change for trv.gf_hw_east
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_hw_east/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_hw_east/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '5940383840429'
  alias: Update Danfoss Ally TRV on change for trv.gf_guest-room
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_guest-room/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_guest-room/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '0255767772069'
  alias: Update Danfoss Ally TRV on change for trv.uf_bedroom
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.uf_bedroom/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.uf_bedroom/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
- id: '8399155979492'
  alias: Update Danfoss Ally TRV on change for trv.gf_toilet
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/trv.gf_toilet/set/occupied_heating_setpoint
  - platform: time_pattern
    minutes: '*'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/trv.gf_toilet/get
      payload: '{"occupied_heating_setpoint":"", "local_temperature":""}'
  mode: single
